apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Publish Pipeline

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  publish:
    if: ${{ cloudbees.scm.branch == 'master' || cloudbees.scm.branch == 'alpha' || cloudbees.scm.branch == 'beta' }}
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Setup NPM Authentication
        uses: docker://vlocitybuild
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm whoami

      - name: Get Current Version
        uses: docker://vlocitybuild
        run: |
          CURRENT_VERSION_RELEASE=$(npm show vlocity version 2>/dev/null || echo "0.0.1")
          echo "CURRENT_VERSION=$CURRENT_VERSION_RELEASE" >> $CLOUDBEES_OUTPUTS/env
          echo "Current published version: $CURRENT_VERSION_RELEASE"

      - name: Update Version
        uses: docker://vlocitybuild
        env:
          CI_BRANCH: ${{ cloudbees.scm.branch }}
          CI_COMMIT_MESSAGE: ${{ cloudbees.scm.commit.message }}
        run: |
          CURRENT_VERSION=$(npm show vlocity version 2>/dev/null || echo "0.0.1")
          
          if [ "$CI_BRANCH" == "master" ]; then
            npm version "$CURRENT_VERSION" --no-git-tag-version --allow-same-version
            
            if [[ "$CI_COMMIT_MESSAGE" == *"New Minor Version"* ]]; then
              echo "Bumping minor version"
              npm version minor --no-git-tag-version
            else
              echo "Bumping patch version"
              npm version patch --no-git-tag-version
            fi
          else
            CURRENT_VERSION_BRANCH=$(npm show "vlocity@$CI_BRANCH" version 2>/dev/null || echo "0.0.0")
            
            if [ "$CURRENT_VERSION" \> "$CURRENT_VERSION_BRANCH" ]; then
              npm version "${CURRENT_VERSION}-${CI_BRANCH}" --no-git-tag-version
              npm version prerelease --no-git-tag-version
            else
              npm version "${CURRENT_VERSION_BRANCH}" --no-git-tag-version
              npm version prerelease --no-git-tag-version
            fi
          fi
          
          P_VERSION=$(cat package.json | jq -r '.version')
          echo "P_VERSION=$P_VERSION" >> $CLOUDBEES_OUTPUTS/env
          echo "New version: $P_VERSION"

      - name: Build Package
        uses: docker://vlocitybuild
        if: ${{ cloudbees.scm.branch == 'master' }}
        run: |
          npm run-script build

      - name: Create GitHub Release
        uses: docker://vlocitybuild
        if: ${{ cloudbees.scm.branch == 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_FALLBACK_TOKEN: ${{ secrets.GITHUB_FALLBACK_TOKEN }}
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          P_VERSION=$(cat package.json | jq -r '.version')
          GITHUB_ASSETS="dist/vlocity-linux,dist/vlocity-macos,dist/vlocity-win.exe"
          
          if ! publish-release \
            --notes "$P_VERSION" \
            --token "$GITHUB_TOKEN" \
            --target_commitish "$CI_BRANCH" \
            --owner vlocityinc \
            --repo vlocity_build \
            --name "v$P_VERSION" \
            --tag "v$P_VERSION" \
            --assets "$GITHUB_ASSETS"; then
            
            echo "Trying fallback token..."
            if [ -n "$GITHUB_FALLBACK_TOKEN" ]; then
              publish-release \
                --notes "$P_VERSION" \
                --token "$GITHUB_FALLBACK_TOKEN" \
                --target_commitish "$CI_BRANCH" \
                --owner vlocityinc \
                --repo vlocity_build \
                --name "v$P_VERSION" \
                --tag "v$P_VERSION" \
                --assets "$GITHUB_ASSETS"
            else
              echo "Warning: GitHub release failed, no fallback token"
            fi
          fi

      - name: Publish to NPM
        uses: docker://vlocitybuild
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          P_VERSION=$(cat package.json | jq -r '.version')
          
          if [ "$CI_BRANCH" == "master" ]; then
            npm publish . --access public
            echo "Published $P_VERSION to NPM (latest)"
          else
            npm publish . --tag="$CI_BRANCH" --access public
            echo "Published $P_VERSION to NPM (tag: $CI_BRANCH)"
          fi
