apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test and Publish Pipeline

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  # =============================================================================
  # TEST JOB - Must pass before publish runs
  # =============================================================================
  test:
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Install SF CLI and Authenticate
        uses: docker://node:18
        env:
          SFDX_AUTH_URL: ${{ vars.SFDX_AUTH_URL }}
        run: |
          echo "=== Installing jq and SF CLI ==="
          apt-get update && apt-get install -y jq
          npm install -g @salesforce/cli
          sf --version
          
          echo "=== Authenticating to Salesforce ==="
          echo "$SFDX_AUTH_URL" > /tmp/authurl.txt
          sf org login sfdx-url --sfdx-url-file /tmp/authurl.txt --json 2>/dev/null > /tmp/auth_result.json
          
          SF_USERNAME=$(cat /tmp/auth_result.json | jq -r '.result.username')
          echo "Authenticated as: $SF_USERNAME"
          
          sf force alias set VB_TEST_ORG="$SF_USERNAME"
          rm -f /tmp/authurl.txt

      - name: Install Dependencies
        uses: docker://node:18
        run: |
          echo "=== Installing npm dependencies ==="
          npm install

      - name: Run Unit Tests
        uses: docker://node:18
        run: |
          echo "=== Running Unit Tests ==="
          npm run-script unitTest

      - name: Link Package and Run Vlocity Test Job Verbose
        uses: docker://node:18
        env:
          SFDX_AUTH_URL: ${{ vars.SFDX_AUTH_URL }}
        run: |
          apt-get update && apt-get install -y jq
          npm install -g @salesforce/cli
          
          echo "=== Re-authenticating to Salesforce ==="
          echo "$SFDX_AUTH_URL" > /tmp/authurl.txt
          sf org login sfdx-url --sfdx-url-file /tmp/authurl.txt --json 2>/dev/null > /tmp/auth_result.json
          SF_USERNAME=$(cat /tmp/auth_result.json | jq -r '.result.username')
          rm -f /tmp/authurl.txt
          
          echo "=== Installing dependencies and linking package ==="
          npm install
          npm link
          
          echo "=== Running Vlocity Test Job (Verbose) ==="
          echo "SF Username: $SF_USERNAME"
          vlocity -sfdx.username "$SF_USERNAME" runTestJob --verbose

      - name: Link Package and Run Vlocity Test Job JSON
        uses: docker://node:18
        env:
          SFDX_AUTH_URL: ${{ vars.SFDX_AUTH_URL }}
        run: |
          apt-get update && apt-get install -y jq
          npm install -g @salesforce/cli
          
          echo "=== Re-authenticating to Salesforce ==="
          echo "$SFDX_AUTH_URL" > /tmp/authurl.txt
          sf org login sfdx-url --sfdx-url-file /tmp/authurl.txt --json 2>/dev/null > /tmp/auth_result.json
          SF_USERNAME=$(cat /tmp/auth_result.json | jq -r '.result.username')
          rm -f /tmp/authurl.txt
          
          echo "=== Installing dependencies and linking package ==="
          npm install
          npm link
          
          echo "=== Running JSON Jobs - Takes up to 10 minutes ==="
          vlocity -sfdx.username "$SF_USERNAME" runTestJob --json | jq .

      - name: Test Summary
        uses: docker://node:18
        run: |
          echo "=========================================="
          echo "TEST PIPELINE - PASSED"
          echo "=========================================="

  # =============================================================================
  # PUBLISH JOB - Only runs if test job passes (needs: test)
  # =============================================================================
  publish:
    needs: test
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Get and Update Version
        uses: docker://node:18
        env:
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          # Install jq
          apt-get update && apt-get install -y jq
          
          # Get commit message using git command
          CI_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $CI_COMMIT_MESSAGE"
          
          CURRENT_VERSION=$(npm show vlocity version 2>/dev/null || echo "0.0.1")
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$CI_BRANCH" == "master" ]; then
            npm version "$CURRENT_VERSION" --no-git-tag-version --allow-same-version
            if [[ "$CI_COMMIT_MESSAGE" == *"New Minor Version"* ]]; then
              echo "Bumping minor version"
              npm version minor --no-git-tag-version
            else
              echo "Bumping patch version"
              npm version patch --no-git-tag-version
            fi
          else
            CURRENT_VERSION_BRANCH=$(npm show "vlocity@$CI_BRANCH" version 2>/dev/null || echo "0.0.0")
            if [ "$CURRENT_VERSION" \> "$CURRENT_VERSION_BRANCH" ]; then
              npm version "${CURRENT_VERSION}-${CI_BRANCH}" --no-git-tag-version
            else
              npm version "${CURRENT_VERSION_BRANCH}" --no-git-tag-version
            fi
            npm version prerelease --no-git-tag-version
          fi
          
          NEW_VERSION=$(cat package.json | jq -r '.version')
          echo "New version: $NEW_VERSION"

      - name: Install Dependencies
        uses: docker://node:18
        run: |
          npm install

      - name: Build Package
        uses: docker://node:18
        if: ${{ cloudbees.scm.branch == 'master' }}
        run: |
          npm run-script build

      - name: Create GitHub Release
        uses: docker://node:18
        if: ${{ cloudbees.scm.branch == 'master' }}
        env:
          GITHUB_TOKEN: ${{ vars.GITHUB_TOKEN }}
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          # Install jq and publish-release tool
          apt-get update && apt-get install -y jq curl
          npm install -g publish-release
          
          NEW_VERSION=$(cat package.json | jq -r '.version')
          GITHUB_ASSETS="dist/vlocity-linux,dist/vlocity-macos,dist/vlocity-win.exe"
          
          echo "Creating GitHub release v$NEW_VERSION..."
          
          # Check if release already exists
          EXISTING_RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/vlocityinc/vlocity_build/releases/tags/v$NEW_VERSION" || echo "{}")
          
          if echo "$EXISTING_RELEASE" | grep -q '"id"'; then
            echo "Release v$NEW_VERSION already exists. Skipping creation."
          else
            publish-release \
              --notes "$NEW_VERSION" \
              --token "$GITHUB_TOKEN" \
              --target_commitish "$CI_BRANCH" \
              --owner vlocityinc \
              --repo vlocity_build \
              --name "v$NEW_VERSION" \
              --tag "v$NEW_VERSION" \
              --assets "$GITHUB_ASSETS" || echo "GitHub release creation failed, continuing..."
            
            echo "GitHub release created: v$NEW_VERSION"
          fi

      # =========================================================================
      # NPM PUBLISH - CURRENTLY DISABLED
      # =========================================================================
      # - name: Publish to NPM
      #   uses: docker://node:18
      #   env:
      #     NPM_TOKEN: ${{ vars.NPM_TOKEN }}
      #     CI_BRANCH: ${{ cloudbees.scm.branch }}
      #   run: |
      #     apt-get update && apt-get install -y jq
      #     echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      #     npm whoami
      #     NEW_VERSION=$(cat package.json | jq -r '.version')
      #     
      #     if [ "$CI_BRANCH" == "master" ]; then
      #       npm publish . --access public
      #       echo "Published $NEW_VERSION to NPM (latest)"
      #     else
      #       npm publish . --tag="$CI_BRANCH" --access public
      #       echo "Published $NEW_VERSION to NPM (tag: $CI_BRANCH)"
      #     fi

      - name: Publish Summary
        uses: docker://node:18
        run: |
          apt-get update && apt-get install -y jq
          NEW_VERSION=$(cat package.json | jq -r '.version')
          echo "=========================================="
          echo "PUBLISH PIPELINE - COMPLETED"
          echo "=========================================="
          echo "Version: $NEW_VERSION"
          echo "GitHub Release: v$NEW_VERSION (master only)"
          echo "NPM Publish: SKIPPED (token expired)"
          echo "=========================================="
