apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Publish Pipeline

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  publish:
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Get and Update Version
        uses: docker://node:18
        env:
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          # Get commit message using git command
          CI_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $CI_COMMIT_MESSAGE"
          
          CURRENT_VERSION=$(npm show vlocity version 2>/dev/null || echo "0.0.1")
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$CI_BRANCH" == "master" ]; then
            npm version "$CURRENT_VERSION" --no-git-tag-version --allow-same-version
            if [[ "$CI_COMMIT_MESSAGE" == *"New Minor Version"* ]]; then
              echo "Bumping minor version"
              npm version minor --no-git-tag-version
            else
              echo "Bumping patch version"
              npm version patch --no-git-tag-version
            fi
          else
            CURRENT_VERSION_BRANCH=$(npm show "vlocity@$CI_BRANCH" version 2>/dev/null || echo "0.0.0")
            if [ "$CURRENT_VERSION" \> "$CURRENT_VERSION_BRANCH" ]; then
              npm version "${CURRENT_VERSION}-${CI_BRANCH}" --no-git-tag-version
            else
              npm version "${CURRENT_VERSION_BRANCH}" --no-git-tag-version
            fi
            npm version prerelease --no-git-tag-version
          fi
          
          NEW_VERSION=$(cat package.json | jq -r '.version')
          echo "New version: $NEW_VERSION"

      - name: Install Dependencies
        uses: docker://node:18
        run: |
          npm install

      - name: Build Package
        uses: docker://node:18
        if: ${{ cloudbees.scm.branch == 'master' }}
        run: |
          npm run-script build

      - name: Create GitHub Release
        uses: docker://node:18
        if: ${{ cloudbees.scm.branch == 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          # Install publish-release tool
          npm install -g publish-release
          
          NEW_VERSION=$(cat package.json | jq -r '.version')
          GITHUB_ASSETS="dist/vlocity-linux,dist/vlocity-macos,dist/vlocity-win.exe"
          
          echo "Creating GitHub release v$NEW_VERSION..."
          
          # Check if release already exists
          EXISTING_RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/vlocityinc/vlocity_build/releases/tags/v$NEW_VERSION")
          
          if echo "$EXISTING_RELEASE" | grep -q '"id"'; then
            echo "Release v$NEW_VERSION already exists. Skipping creation."
          else
            publish-release \
              --notes "$NEW_VERSION" \
              --token "$GITHUB_TOKEN" \
              --target_commitish "$CI_BRANCH" \
              --owner vlocityinc \
              --repo vlocity_build \
              --name "v$NEW_VERSION" \
              --tag "v$NEW_VERSION" \
              --assets "$GITHUB_ASSETS"
            
            echo "GitHub release created: v$NEW_VERSION"
          fi

      # =========================================================================
      # NPM PUBLISH - CURRENTLY DISABLED
      # 
      # npm token has expired and we're waiting for npm team access.
      # To re-enable when token is available:
      #   1. Add new NPM_TOKEN to Unify secrets
      #   2. Uncomment the step below
      # =========================================================================
      # - name: Publish to NPM
      #   uses: docker://node:18
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     CI_BRANCH: ${{ cloudbees.scm.branch }}
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      #     npm whoami
      #     NEW_VERSION=$(cat package.json | jq -r '.version')
      #     
      #     if [ "$CI_BRANCH" == "master" ]; then
      #       npm publish . --access public
      #       echo "Published $NEW_VERSION to NPM (latest)"
      #     else
      #       npm publish . --tag="$CI_BRANCH" --access public
      #       echo "Published $NEW_VERSION to NPM (tag: $CI_BRANCH)"
      #     fi

      - name: Summary
        uses: docker://node:18
        run: |
          NEW_VERSION=$(cat package.json | jq -r '.version')
          echo "=========================================="
          echo "Publish Pipeline - COMPLETED"
          echo "=========================================="
          echo "Version: $NEW_VERSION"
          echo "GitHub Release: v$NEW_VERSION (master only)"
          echo "NPM Publish: SKIPPED (token expired - waiting for npm team)"
          echo "=========================================="
