apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Publish Pipeline

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  publish:
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Setup NPM Authentication
        uses: docker://node:18
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm whoami || echo "NPM auth check skipped"

      - name: Get and Update Version
        uses: docker://node:18
        env:
          CI_BRANCH: ${{ cloudbees.scm.branch }}
          CI_COMMIT_MESSAGE: ${{ cloudbees.scm.commit.message }}
        run: |
          CURRENT_VERSION=$(npm show vlocity version 2>/dev/null || echo "0.0.1")
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$CI_BRANCH" == "master" ]; then
            npm version "$CURRENT_VERSION" --no-git-tag-version --allow-same-version
            if [[ "$CI_COMMIT_MESSAGE" == *"New Minor Version"* ]]; then
              npm version minor --no-git-tag-version
            else
              npm version patch --no-git-tag-version
            fi
          else
            CURRENT_VERSION_BRANCH=$(npm show "vlocity@$CI_BRANCH" version 2>/dev/null || echo "0.0.0")
            if [ "$CURRENT_VERSION" \> "$CURRENT_VERSION_BRANCH" ]; then
              npm version "${CURRENT_VERSION}-${CI_BRANCH}" --no-git-tag-version
            else
              npm version "${CURRENT_VERSION_BRANCH}" --no-git-tag-version
            fi
            npm version prerelease --no-git-tag-version
          fi
          
          NEW_VERSION=$(cat package.json | jq -r '.version')
          echo "New version: $NEW_VERSION"

      - name: Install Dependencies
        uses: docker://node:18
        run: |
          npm install

      - name: Build Package
        uses: docker://node:18
        run: |
          npm run-script build || echo "Build step skipped or failed"

      - name: Publish to NPM (Dry Run for Testing)
        uses: docker://node:18
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          NEW_VERSION=$(cat package.json | jq -r '.version')
          
          echo "Would publish version: $NEW_VERSION"
          echo "Branch: $CI_BRANCH"
          
          # DRY RUN - Remove --dry-run when ready to actually publish
          if [ "$CI_BRANCH" == "master" ]; then
            npm publish . --access public --dry-run
          else
            npm publish . --tag="$CI_BRANCH" --access public --dry-run
          fi
          
          echo "Dry run complete. Remove --dry-run to actually publish."