apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  test:
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Install and Test
        uses: docker://node:18
        run: |
          npm install
          npm run-script unitTest